--- #YAML:1.0
name:                HTML-StripScripts
version:             1.00
abstract:            Strip scripting constructs out of HTML
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Nick Cleaton <nick@cleaton.net>, Clinton Gormley <clint@traveljury.com>
